export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_CURRENT_QUERY = "SET_CURRENT_QUERY";

export const SET_CURRENT_NOTIFICATION = "SET_CURRENT_NOTIFICATION";
export const CLEAR_CURRENT_NOTIFICATION = "CLEAR_CURRENT_NOTIFICATION";