export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_CURRENT_QUERY = "SET_CURRENT_QUERY";

export const SET_CURRENT_NOTIFICATION = "SET_CURRENT_NOTIFICATION";
export const CLEAR_CURRENT_NOTIFICATION = "CLEAR_CURRENT_NOTIFICATION";

export const TOGGLE_SIDE_PANEL = "TOGGLE_SIDE_PANEL";
export const TOGGLE_META_PANEL = "TOGGLE_META_PANEL";

export const SET_WINDOW_SIZE = "SET_WINDOW_SIZE";